version: '3.9'

services:
  postgresdb:
    env_file: .env.production
    image: postgres
    # build:
    #   context: .
    #   dockerfile: database.Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - scrapie-network
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - scrapie-network
  
  web:
    build:
      context: .
      dockerfile: production.Dockerfile
    restart: always
    env_file: .env.production
    ports:
      - "8000:8000"
    depends_on:
      - postgresdb
      - redis
    networks:
      - scrapie-network
    links:
      - postgresdb
      - redis

networks:
  scrapie-network:
    driver: bridge